# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reekomer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='file_upload',
        ),
    ]
